set-option -g status-position top

# opted to use default keybind for transferable knowledge

# Fn Key Binds - Shoutout to Starcraft
bind-key -n F1 select-window -t 1
bind-key -n F2 select-window -t 2
bind-key -n F3 select-window -t 3
bind-key -n F4 select-window -t 4
bind-key -n F5 select-window -t 5
bind-key -n F6 select-window -t 6
bind-key -n F7 select-window -t 7
bind-key -n F8 select-window -t 8
bind-key -n F9 select-window -t 9
bind-key -n F10 select-window -t 10

bind v split-window -h
bind s split-window -v

bind-key -n C-M-d detach-client
bind-key -n C-M-q kill-pane
bind-key -n C-M-n new-window
bind-key -n C-M-, command-prompt -I "#W" "rename-window '%%'"
bind-key -n C-M-t choose-tree -Zs # ctrl alt tab to change sessions
bind-key -n C-M-c command-prompt -p "New session name:" "new-session -s '%%'"
bind-key -n C-M-z switch-client -p     # Ctrl+Alt+z to previous session
bind-key -n C-M-x switch-client -n     # Ctrl+Alt+x to next session

# Split window bindings with Ctrl+Alt
bind-key -n C-M-v split-window -h    # Ctrl+Alt+v for vertical split
bind-key -n C-M-s split-window -v    # Ctrl+Alt+s for horizontal split

# Navigate splits using Vim-like hjkl keys
bind-key -n C-M-h select-pane -L     # Ctrl+Alt+h to move left
bind-key -n C-M-j select-pane -D     # Ctrl+Alt+j to move down
bind-key -n C-M-k select-pane -U     # Ctrl+Alt+k to move up
bind-key -n C-M-l select-pane -R     # Ctrl+Alt+l to move right

# Swap panes in direction with Ctrl+Alt+Shift
bind-key -n C-M-H run-shell 'P=$(tmux display -p "#{pane_id}"); tmux select-pane -L && tmux swap-pane -s "$P"'
bind-key -n C-M-J run-shell 'P=$(tmux display -p "#{pane_id}"); tmux select-pane -D && tmux swap-pane -s "$P"'
bind-key -n C-M-K run-shell 'P=$(tmux display -p "#{pane_id}"); tmux select-pane -U && tmux swap-pane -s "$P"'
bind-key -n C-M-L run-shell 'P=$(tmux display -p "#{pane_id}"); tmux select-pane -R && tmux swap-pane -s "$P"'

# start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set -g set-clipboard on # use system clipboard
set -g renumber-windows on
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_text "#W"

set -g @plugin 'catppuccin/tmux#latest'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-strategy-nvim 'session'

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_host_color "#{@thm_mauve}"
set -g @catppuccin_session_color "#{@thm_teal}"
set -g @catppuccin_status_left_separator ""
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_connect_separator "no"

set -g status-left ""
set -g status-right-length 100

run '~/.tmux/plugins/tpm/tpm'

set -g status-right "#{E:@catppuccin_status_host}"
set -ag status-right "#{E:@catppuccin_status_session}"
