#!/usr/bin/env python3
"""Build the `neu` cursor theme from theme/tokens.json.

    python3 theme/cursor/gen_cursor.py            # build into theme/cursor/build
    python3 theme/cursor/gen_cursor.py --sheet    # also write a contact sheet to /tmp

Needs only rsvg-convert (already installed). The Xcursor container is written by
theme/cursor/xcursor.py rather than xcursorgen, so nothing has to be installed and
nothing needs sudo -- see CURSOR_NEU.md.

Produces two themes, both called `neu`, in separate roots because they must not
share a `cursors/` directory -- Xcursor would try to parse hyprcursor's .hlc files:

  build/xcursor/neu/   -> ~/.icons/neu               XWayland, GTK, Qt, X11
  build/hypr/neu/      -> ~/.local/share/icons/neu   Hyprland's native cursors
  build/hypr-src/      hyprcursor source (SVG + meta.hl), input to hyprcursor-util
"""

from __future__ import annotations

import json
import math
import pathlib
import shutil
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent.parent
sys.path.insert(0, str(HERE))

import shapes  # noqa: E402
import xcursor  # noqa: E402

TOKENS = json.loads((ROOT / "theme" / "tokens.json").read_text())
BUILD = HERE / "build"

# Nominal sizes an Xcursor theme should carry. 36 is in there because
# hyprland.lua sets XCURSOR_SIZE=36, so that size is served without rescaling.
SIZES = [24, 32, 36, 48, 64, 96]

GRID = 24.0  # the coordinate space shapes.py draws in


def svg(body: str, size: int, rotate: float = 0.0) -> str:
    """One cursor frame.

    The shape is drawn twice: a dilated pass in --neu-accent-text makes the edge,
    then a fill pass in --neu-text. That is the two-layer trick every cursor theme
    uses for its outline, and it is why shapes.py is fill-only geometry -- a path
    carrying its own stroke-width would not dilate with the group.
    """
    t = TOKENS
    fill = t["surface"]["text"]
    edge = t["brand"]["primary"]
    shadow = t["surface"]["shadowDark"]
    xform = f' transform="rotate({rotate:.1f} 12 12)"' if rotate else ""
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}"
     viewBox="0 0 {GRID:.0f} {GRID:.0f}">
  <defs>
    <filter id="cast" x="-60%" y="-60%" width="240%" height="240%"
            color-interpolation-filters="sRGB">
      <feDropShadow dx="0.9" dy="1.1" stdDeviation="0.9"
                    flood-color="{shadow}" flood-opacity="0.75"/>
    </filter>
  </defs>
  <g filter="url(#cast)"{xform}>
    <g fill="{edge}" stroke="{edge}" stroke-width="2.6"
       stroke-linejoin="round" stroke-linecap="round">
      {body}
    </g>
    <g fill="{fill}">
      {body}
    </g>
  </g>
</svg>
"""


def rasterize(svg_text: str, size: int) -> bytes:
    """SVG -> straight RGBA bytes."""
    png = subprocess.run(["rsvg-convert", "-w", str(size), "-h", str(size)],
                         input=svg_text.encode(), capture_output=True, check=True).stdout
    raw = subprocess.run(["ffmpeg", "-loglevel", "error", "-i", "pipe:0",
                          "-f", "rawvideo", "-pix_fmt", "rgba", "-"],
                         input=png, capture_output=True, check=True).stdout
    if len(raw) != size * size * 4:
        raise RuntimeError(f"expected {size*size*4} bytes, got {len(raw)}")
    return raw


def build_cursor(name: str) -> bytes:
    hx, hy, body, frames = shapes.SHAPES[name]
    images = []
    for size in SIZES:
        scale = size / GRID
        for f in range(frames):
            rot = 360.0 * f / frames if frames > 1 else 0.0
            rgba = rasterize(svg(body, size, rot), size)
            images.append(xcursor.Image(
                nominal=size, width=size, height=size,
                xhot=min(size - 1, round(hx * scale)),
                yhot=min(size - 1, round(hy * scale)),
                # The DS spinner is 0.8s for a full turn.
                delay=round(TOKENS["motion"]["spinnerMs"] / frames) if frames > 1 else 0,
                pixels=xcursor.rgba_to_argb(rgba)))
    return xcursor.build(images)


def main(argv):
    theme = BUILD / "xcursor" / "neu"
    cursors = theme / "cursors"
    if BUILD.exists():
        shutil.rmtree(BUILD)
    cursors.mkdir(parents=True)

    for name in shapes.SHAPES:
        (cursors / name).write_bytes(build_cursor(name))
        print(f"  + {name}")

    links = 0
    for target, names in shapes.ALIASES.items():
        for alias in names:
            link = cursors / alias
            if link.exists() or link.is_symlink():
                continue
            link.symlink_to(target)
            links += 1

    (theme / "index.theme").write_text(
        "[Icon Theme]\n"
        "Name=neu\n"
        "Comment=@rgtv/neu -- generated by theme/cursor/gen_cursor.py\n"
        "Inherits=Adwaita\n")

    print(f"\n  {len(shapes.SHAPES)} cursors, {links} aliases, sizes {SIZES}")
    build_hyprcursor(theme)

    if "--sheet" in argv:
        contact_sheet()
    return 0


def build_hyprcursor(_theme: pathlib.Path):
    """Hyprland's native cursor path. Skipped if hyprcursor-util is absent."""
    util = shutil.which("hyprcursor-util")
    if not util:
        print("  !  hyprcursor-util not found; Xcursor theme only")
        return
    src = BUILD / "hypr-src"
    (src / "cursors").mkdir(parents=True)
    (src / "manifest.hl").write_text(
        'name = neu\n'
        'description = @rgtv/neu cursor, generated from theme/tokens.json\n'
        'version = 1\n'
        'cursors_directory = cursors\n')
    for name, (hx, hy, body, frames) in shapes.SHAPES.items():
        d = src / "cursors" / name
        d.mkdir()
        overrides = "".join(f"define_override = {a}\n"
                            for a in shapes.ALIASES.get(name, []))
        sizes = ""
        for f in range(frames):
            rot = 360.0 * f / frames if frames > 1 else 0.0
            (d / f"{f}.svg").write_text(svg(body, 64, rot))
            delay = round(TOKENS["motion"]["spinnerMs"] / frames) if frames > 1 else 0
            sizes += f"define_size = 0, {f}.svg, {delay}\n" if frames > 1 else \
                     f"define_size = 0, {f}.svg\n"
        (d / "meta.hl").write_text(
            f"resize_algorithm = bilinear\n"
            f"hotspot_x = {hx / GRID:.4f}\n"
            f"hotspot_y = {hy / GRID:.4f}\n"
            f"{sizes}{overrides}")
    out = subprocess.run([util, "--create", str(src), "--output", str(BUILD)],
                         capture_output=True, text=True)
    # hyprcursor-util writes <output>/theme_<name>/{manifest.hl,cursors/*.hlc}
    made = BUILD / "theme_neu"
    dest = BUILD / "hypr" / "neu"
    if (made / "cursors").exists():
        dest.parent.mkdir(parents=True, exist_ok=True)
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(made, dest)
        shutil.rmtree(made)
        n = len(list((dest / "cursors").iterdir()))
        print(f"  + hyprcursor theme ({n} shapes)")
    else:
        print(f"  !  hyprcursor-util: {(out.stderr or out.stdout).strip()[:200]}")


def contact_sheet():
    """All shapes at 96px on the neu ground, for eyeballing."""
    cells = []
    for i, (name, (hx, hy, body, frames)) in enumerate(shapes.SHAPES.items()):
        png = subprocess.run(["rsvg-convert", "-w", "96", "-h", "96"],
                             input=svg(body, 96).encode(), capture_output=True).stdout
        p = pathlib.Path(f"/tmp/cur_{i:02d}.png")
        p.write_bytes(png)
        cells.append(str(p))
    subprocess.run(["ffmpeg", "-loglevel", "error", "-y"] +
                   sum([["-i", c] for c in cells], []) +
                   ["-filter_complex",
                    f"color=c=0x141414:s={len(cells)*104}x104[bg];" +
                    "".join(f"[{i}:v]pad=104:104:4:4:0x00000000[c{i}];" for i in range(len(cells))) +
                    "[bg]" + "".join(f"[c{i}]overlay={i*104}:0[b{i}];[b{i}]" for i in range(len(cells)))
                    .rstrip("[b%d];[b%d]" % (len(cells)-1, len(cells)-1)) + "null[out]",
                    "-map", "[out]", "-frames:v", "1", "/tmp/cursor_sheet.png"],
                   capture_output=True)
    print("  contact sheet: /tmp/cursor_sheet.png")


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
