pragma Singleton

import QtQuick
import Quickshell

// generated by theme/gen.py from theme/tokens.json; do not edit
//
// Nerd-font glyphs, written as escapes rather than literal characters.
// Every codepoint here is verified present in UbuntuMono Nerd Font.
Singleton {
    readonly property var batteryRamp: ["\udb80\udc8e", "\udb80\udc7a", "\udb80\udc7b", "\udb80\udc7c", "\udb80\udc7d", "\udb80\udc7e", "\udb80\udc7f", "\udb80\udc7f", "\udb80\udc81", "\udb80\udc82", "\udb80\udc79"]
    readonly property var batteryCharging: ["\udb82\udc9c", "\udb80\udc86", "\udb80\udc87", "\udb80\udc88", "\udb82\udc9d", "\udb80\udc89", "\udb82\udc9e", "\udb80\udc8a", "\udb80\udc8b"]
    readonly property string batteryFull: "\udb85\udfe2"
    readonly property var wifiRamp: ["\udb82\udd2f", "\udb82\udd1f", "\udb82\udd22", "\udb82\udd25", "\udb82\udd28"]
    readonly property string wifiOff: "\udb82\udd2e"
    readonly property string ethernet: "\uef44"
    readonly property string volMuted: "\ueee8"
    readonly property string volLow: "\uf027"
    readonly property string volHigh: "\uf028"
    readonly property string headphones: "\uf025"
    readonly property string play: "\uf04b"
    readonly property string pause: "\uf04c"
    readonly property string music: "\uf001"
    readonly property string menu: "\uf0c9"
    readonly property string search: "\uf002"
    readonly property string chevronDown: "\uf078"
    readonly property string chevronRight: "\uf054"
    readonly property string power: "\uf011"
    readonly property string cog: "\uf013"
    readonly property string cpu: "\uf2db"
    readonly property string memory: "\udb80\udf5b"
    readonly property string disk: "\uf0a0"
    readonly property string clock: "\uf017"
    readonly property string calendar: "\uf073"
    readonly property string bell: "\uf0f3"
    readonly property string moon: "\uf186"
    readonly property string sun: "\uf185"
    readonly property string check: "\uf058"
    readonly property string times: "\uf057"
    readonly property string warning: "\uf071"
    readonly property string spinner: "\uf1ce"
    readonly property string refresh: "\uf021"
    readonly property string git: "\uf1d3"
    readonly property string server: "\uf233"
    readonly property string terminal: "\uf120"
    readonly property string folder: "\uf07b"
    readonly property string app: "\uf0c8"
    readonly property string trash: "\uf1f8"
    readonly property string workspace: "\uf009"
    readonly property string bluetooth: "\uf294"
    readonly property string wifiIcon: "\uf1eb"
    readonly property string thermometer: "\uf2c9"
    readonly property string firefox: "\uf269"
    readonly property string chrome: "\uf268"
    readonly property string video: "\uf03d"
    readonly property string database: "\uf1c0"
    readonly property string clipboard: "\uf0ea"
    readonly property string code: "\uf121"
    readonly property string files: "\uf07c"
    readonly property string tv: "\uf26c"

    /** Pick from a low->high ramp by a 0..1 fraction. */
    function ramp(list, frac) {
        if (!list || list.length === 0) return "";
        const i = Math.round(Math.max(0, Math.min(1, frac)) * (list.length - 1));
        return list[i];
    }
}
