pragma Singleton

import QtQuick
import Quickshell

// generated by theme/gen.py from theme/tokens.json; do not edit
//
// @rgtv/neu v3.1.0 design tokens. Depth in this system comes from SHADOW,
// not surface contrast -- the three surface levels are only 4 values apart
// on purpose. Raised = pressable, inset = active/held, flat = disabled;
// see NeuSurface.qml, and don't break that grammar for decoration.
Singleton {
    // ---- surfaces -------------------------------------------------
    readonly property color neuBg: "#141414"
    readonly property color neuBgComponent: "#171717"
    readonly property color neuBgCard: "#181818"
    readonly property color neuHoverHighlight: "#232323"
    readonly property color neuShadowDark: "#000000"
    readonly property color neuShadowLight: "#555555"

    // ---- text -----------------------------------------------------
    readonly property color neuText: "#cccccc"
    readonly property color neuTextMuted: "#999999"
    readonly property color neuTextDim: "#888888"
    readonly property color neuHairline: "#38888888"

    // ---- brand ----------------------------------------------------
    readonly property color neuAccentText: "#8b2fe0"
    readonly property color neuAccent: "#998b2fe0"
    readonly property color neuAccentSecondaryText: "#ff2e9a"
    readonly property color neuAccentSecondary: "#99ff2e9a"
    readonly property color neuAccentTertiaryText: "#15cdc3"
    readonly property color neuAccentTertiary: "#9915cdc3"
    readonly property color neuAccentLightest: "#bc97f3"
    readonly property color neuAccentLighter: "#ab79ee"
    readonly property color neuAccentLight: "#9b58e7"
    readonly property color neuAccentDark: "#6f24b4"
    readonly property color neuAccentDarker: "#54198a"
    readonly property color neuAccentDarkest: "#3a0f63"
    readonly property color neuSecondaryLightest: "#ff9cc6"
    readonly property color neuSecondaryLighter: "#ff7eb7"
    readonly property color neuSecondaryLight: "#ff5da9"
    readonly property color neuSecondaryDark: "#ce237b"
    readonly property color neuSecondaryDarker: "#9e185e"
    readonly property color neuSecondaryDarkest: "#710e42"
    readonly property color neuTertiaryLightest: "#9de4de"
    readonly property color neuTertiaryLighter: "#7eddd5"
    readonly property color neuTertiaryLight: "#58d5cc"
    readonly property color neuTertiaryDark: "#0fa59d"
    readonly property color neuTertiaryDarker: "#087e78"
    readonly property color neuTertiaryDarkest: "#045a55"

    // ---- status (stays Catppuccin, as in the DS) -------------------
    readonly property color neuSuccessText: "#a6e3a1"
    readonly property color neuSuccess: "#b2a6e3a1"
    readonly property color neuErrorText: "#f38ba8"
    readonly property color neuError: "#b2f38ba8"
    readonly property color neuInfoText: "#89b4fa"
    readonly property color neuInfo: "#9989b4fa"
    readonly property color neuWarningText: "#fab387"
    readonly property color neuWarning: "#99fab387"

    // ---- categorical domain slots ---------------------------------
    readonly property color neuDomain1: "#ee204d"
    readonly property color neuDomain2: "#ff7538"
    readonly property color neuDomain3: "#ffc60a"
    readonly property color neuDomain4: "#28c76f"
    readonly property color neuDomain5: "#00c2de"
    readonly property color neuDomain6: "#1f75fe"
    readonly property color neuDomain7: "#7c3aed"
    readonly property color neuDomain8: "#ff49c0"

    // ---- shadow ramp (offset / blur / reach) ----------------------
    // reach = offset + blur: space siblings by it so their shadows meet
    // rather than overlap. Straight from --neu-shadow-*-gap.
    readonly property int shadowXxsOffset: 1
    readonly property int shadowXxsBlur: 3
    readonly property int shadowXxsGap: 4
    readonly property int shadowXsOffset: 2
    readonly property int shadowXsBlur: 4
    readonly property int shadowXsGap: 6
    readonly property int shadowSOffset: 3
    readonly property int shadowSBlur: 6
    readonly property int shadowSGap: 9
    readonly property int shadowMOffset: 4
    readonly property int shadowMBlur: 8
    readonly property int shadowMGap: 12
    readonly property int shadowLOffset: 5
    readonly property int shadowLBlur: 10
    readonly property int shadowLGap: 15
    readonly property int shadowXlOffset: 7
    readonly property int shadowXlBlur: 14
    readonly property int shadowXlGap: 21
    readonly property int insetXsOffset: 2
    readonly property int insetXsBlur: 4
    readonly property int insetSOffset: 3
    readonly property int insetSBlur: 6
    readonly property int insetMOffset: 4
    readonly property int insetMBlur: 8
    readonly property int insetLOffset: 5
    readonly property int insetLBlur: 12

    // ---- scale ----------------------------------------------------
    readonly property int sizeXxs: 2
    readonly property int sizeXs: 4
    readonly property int sizeS: 8
    readonly property int sizeM: 12
    readonly property int sizeL: 16
    readonly property int sizeXl: 24
    readonly property int sizeXxl: 32
    readonly property int radiusS: 8
    readonly property int radiusM: 16
    readonly property int radiusL: 32
    readonly property int borderXs: 1
    readonly property int borderS: 2
    readonly property int borderM: 3
    readonly property int borderL: 4
    readonly property int focusRing: 3

    // ---- type -----------------------------------------------------
    readonly property string fontFamily: "UbuntuMono Nerd Font"
    readonly property string fontUi: "Adwaita Sans"
    readonly property int fontXs: 11
    readonly property int fontS: 13
    readonly property int fontM: 14
    readonly property int fontL: 16
    readonly property int fontXl: 18
    readonly property int fontXxl: 20
    readonly property int fontXxxl: 26
    readonly property int weightMedium: 500
    readonly property int weightSemibold: 600
    readonly property int weightBold: 700
    readonly property real trackingSection: 0.1
    readonly property real trackingGroup: 0.06
    readonly property real trackingHeader: 0.05
    readonly property real trackingStat: 0.04
    readonly property real trackingCta: 0.01

    // ---- motion / z -----------------------------------------------
    readonly property int fastMs: 150
    readonly property int baseMs: 200
    readonly property int defaultMs: 300
    readonly property int slowMs: 500
    readonly property int rainbowMs: 20000
    readonly property int spinnerMs: 800
    readonly property int shimmerMs: 1800
    readonly property int toastInMs: 350
    readonly property int toastOutMs: 300
    readonly property int zRaised: 10
    readonly property int zSticky: 100
    readonly property int zDropdown: 200
    readonly property int zOverlay: 1000
    readonly property int zToast: 9999

    // ---- desktop --------------------------------------------------
    readonly property int barHeight: 42
    readonly property real barBlurAlpha: 0.97
    readonly property int dockIconPx: 40
    readonly property real dockMagHovered: 1.4
    readonly property real dockMagNeighbour: 1.2
    readonly property int meterSegments: 12
    readonly property string userName: "jwbla"
    readonly property string userInitials: "JW"

    // ---- compatibility aliases ------------------------------------
    // The panes written before this port bind to Catppuccin names. The
    // greyscale ones now resolve to the neu ramp so nothing looks foreign;
    // the status hues are genuinely still Catppuccin.
    readonly property color base: "#141414"
    readonly property color mantle: "#141414"
    readonly property color crust: "#000000"
    readonly property color surface0: "#171717"
    readonly property color surface1: "#232323"
    readonly property color surface2: "#555555"
    readonly property color text: "#cccccc"
    readonly property color subtext1: "#cccccc"
    readonly property color subtext0: "#999999"
    readonly property color overlay2: "#999999"
    readonly property color overlay1: "#999999"
    readonly property color overlay0: "#888888"
    readonly property color primary: "#8b2fe0"
    readonly property color secondary: "#ff2e9a"
    readonly property color lightPrimary: "#9b58e7"
    readonly property color lightestPrimary: "#ab79ee"
    readonly property color darkPrimary: "#54198a"
    readonly property color lightSecondary: "#ff5da9"
    readonly property color lightestSecondary: "#ff7eb7"
    readonly property color darkSecondary: "#9e185e"
    readonly property color sapphire: "#8b2fe0"
    readonly property color rosewater: "#f5e0dc"
    readonly property color flamingo: "#f2cdcd"
    readonly property color pink: "#f5c2e7"
    readonly property color mauve: "#cba6f7"
    readonly property color red: "#f38ba8"
    readonly property color maroon: "#eba0ac"
    readonly property color peach: "#fab387"
    readonly property color yellow: "#f9e2af"
    readonly property color green: "#a6e3a1"
    readonly property color teal: "#94e2d5"
    readonly property color sky: "#89dceb"
    readonly property color blue: "#89b4fa"
    readonly property color lavender: "#b4befe"

    // Near-opaque on purpose. hyprland.lua asks for layer blur behind the
    // neu:* namespaces, but Hyprland 0.56.2 does not honour it, so without a
    // real backdrop a translucent panel just shows sharp text through itself.
    readonly property color panelBg: Qt.rgba(neuBgCard.r, neuBgCard.g, neuBgCard.b, 0.97)
    readonly property color rowBg: neuBgComponent
    readonly property color rowHover: neuHoverHighlight
    readonly property int fontSize: 14
    readonly property int fontSizeSmall: 13
    readonly property int fontSizeHeader: 18
    readonly property int padding: 12
    readonly property int radius: 16
    readonly property int rowHeight: 30
    readonly property int animDuration: 200
}
