-- Hyprland Lua config (format introduced in Hyprland 0.55, replaces hyprland.conf)

-- The @rgtv/neu palette and metrics, generated by ~/dev/dotfiles/theme/gen.py.
-- dofile rather than require: Hyprland does not put the config dir on package.path.
local neu = dofile(os.getenv("HOME") .. "/.config/hypr/neu.lua")
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})
hl.monitor({
    output   = "HDMI-A-1",
    mode     = "preferred",
    position = "1920x0",
    scale    = 1,
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "ghostty"
local fileManager = "dolphin"
-- Spotlight, in the neu shell. wofi stays installed and styled: it is what
-- neu-panic.sh rebinds SUPER+SPACE to, and what --dmenu callers still use.
local menu        = "qs -c commandcenter ipc call spotlight toggle"
local dbman       = "sqlitebrowser"
local freetube    = "flatpak run io.freetubeapp.FreeTube"


-------------------
---- AUTOSTART ----
-------------------

-- Autostart necessary processes (notification daemons, status bars, etc.)
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
    -- The neu shell: bar, dock, launcher, notifications and the Command Center
    -- (SUPER+`) / rgtv glance (SUPER+R) panels. Started through neu-shell.sh
    -- rather than `qs -d` directly so that a shell which fails to come up falls
    -- back to waybar instead of leaving the session with no bar at all.
    hl.exec_cmd("~/.local/bin/neu-shell.sh")
    hl.exec_cmd("hypridle")
    hl.exec_cmd(terminal)
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_SIZE", "36")
hl.env("HYPRCURSOR_SIZE", "36")
-- The generated neu cursor. XCURSOR_THEME covers XWayland/GTK/Qt;
-- HYPRCURSOR_THEME is Hyprland's own native path. Same name, different roots
-- (~/.icons vs ~/.local/share/icons) -- see CURSOR_NEU.md.
hl.env("XCURSOR_THEME", "neu")
hl.env("HYPRCURSOR_THEME", "neu")

-- Force Qt/KDE apps to use qt6ct (dark palette configured in ~/.config/qt6ct)
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        -- Neumorphic shadows need room to fall. --neu-shadow-l reaches 15px
        -- (5 offset + 10 blur), so that is the outer gap; inner gaps are half,
        -- since two neighbours each contribute a shadow.
        gaps_in  = neu.gaps_in,
        gaps_out = neu.gaps_out,

        border_size = neu.border,

        col = {
            -- The brand trio, rotating. This is the desktop's answer to the DS's
            -- `btn-rainbow` halo -- the same "this one is live" cue, at the same
            -- 20s period (see borderangle below).
            active_border = {
                colors = { neu.primary, neu.secondary, neu.tertiary },
                angle = 45,
            },
            -- Neumorphism gets depth from shadow, not outline, so an unfocused
            -- window has no border at all.
            inactive_border = neu.transparent,
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding = neu.rounding,          -- --neu-radius-m

        -- .neu-window sits at 0.97 when inactive, 1 when active.
        active_opacity   = 1.0,
        inactive_opacity = 0.97,

        -- Hyprland casts one shadow, so it gets the DARK half of the neumorphic
        -- pair. The light half only reads against a known surface; over
        -- wallpaper it would look like a halo.
        -- Windows get the LIGHT half of the neumorphic pair.
        --
        -- Hyprland has exactly one shadow slot, so one half of `--neu-shadow-*`
        -- has to go. Measuring the DS's own bake picks the winner: in
        -- ~/dev/.artifacts/ksz/neu-default/atlas/panel.base.png the ground sits at
        -- luminance 20, the light edge at 38 (+18) and the dark edge at 14 (-6).
        -- Against a near-black ground the light half does three times the work,
        -- and the desktop ground is now that same flat neu-bg.
        --
        -- Negative offset puts it up and to the left, where the light is
        -- (`-5px -5px 10px #555` in the CSS pair). Tier `s` rather than `l`: a
        -- window is far larger than a card, and the halo scales with what it
        -- surrounds.
        --
        -- Identical focused and unfocused on purpose -- the animated brand border
        -- is the focus differentiator, not the shadow.
        --
        -- Rejected, each measured: `decoration:glow` (inert -- a magenta glow at
        -- range 30 changes not one pixel); a gradient shadow (renders vertically,
        -- so the right edge came out light at the top); and drawing the true pair
        -- from the shell on a Bottom layer (the layer maps and throws no QML
        -- warning, but nothing renders -- not chased further).
        shadow = {
            enabled        = true,
            range          = neu.shadow_range,
            render_power   = 2,
            offset         = { -neu.shadow_offset, -neu.shadow_offset },
            color          = neu.shadowLight,
            color_inactive = neu.shadowLight,
        },

        blur = {
            enabled  = true,
            size     = 6,
            passes   = 2,
            vibrancy = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },

    -- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
    dwindle = {
        preserve_split = true, -- You probably want this
    },

    -- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
    master = {
        new_status = "master",
    },

    misc = {
        force_default_wallpaper = 0, -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = true, -- If true disables the random hyprland logo / anime girl background. :(
    },
})

-- Animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("myBezier", { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.05} } })
hl.curve("linear",   { type = "bezier", points = { {0, 0},     {1, 1}      } })

-- Retimed to the DS's transition scale. Hyprland speed is in ds (1 = 100ms):
-- --neu-transition 0.3s -> 3, --neu-transition-base 0.2s -> 2.
hl.animation({ leaf = "windows",    enabled = true, speed = neu.speed_default, bezier = "myBezier" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = neu.speed_base,    bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border",     enabled = true, speed = neu.speed_base,    bezier = "default" })
hl.animation({ leaf = "fade",       enabled = true, speed = neu.speed_base,    bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = neu.speed_default, bezier = "default" })
-- The rotating brand border, at `btn-rainbow`'s 20s period.
hl.animation({ leaf = "borderangle", enabled = true, speed = neu.speed_rainbow, bezier = "linear", style = "loop" })

------------------
---- LAYERS ------
------------------

-- Blur behind the shell's layer surfaces.
--
-- NOT CURRENTLY WORKING, and the panels do not rely on it. hl.layer_rule exists
-- in 0.56.2 and this is the documented spelling (see /usr/share/hypr/hyprland.lua),
-- but neither `blur` nor `dim_around` has any observable effect on these
-- namespaces -- checked by putting dim_around on the bar and confirming the
-- screen never dims, and by dropping the panel to 45% alpha and finding the text
-- behind it still perfectly sharp. So the shell's surfaces stay near-opaque,
-- which is the same conclusion the pre-existing Theme.qml comment had reached.
-- Left in place because it is the correct configuration if a later Hyprland
-- honours it; delete it if it is still inert by the time you read this.
hl.layer_rule({
    name  = "neu-blur",
    match = { namespace = "^neu:" },
    blur  = true,
    ignore_alpha = 0.3,
})

hl.layer_rule({
    name  = "neu-quickshell-blur",
    match = { namespace = "^quickshell:" },
    blur  = true,
    ignore_alpha = 0.3,
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout = "us",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = true,
        },
    },

    gestures = {
        workspace_swipe_distance = 300,
        workspace_swipe_invert   = true,
    },
})

hl.gesture({
    fingers   = 3,
    direction = "horizontal",
    action    = "workspace",
})

hl.device({
    name          = "razer-razer-naga-trinity-1",
    sensitivity   = -0.5,
    accel_profile = "flat",
})
hl.device({
    name          = "razer-razer-naga-trinity",
    sensitivity   = -0.5,
    accel_profile = "flat",
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- See https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + Q",     hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C",     hl.dsp.window.close())
hl.bind(mainMod .. " + E",     hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V",     hl.dsp.exec_cmd("copyq toggle"))
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + T",     hl.dsp.layout("togglesplit")) -- dwindle
hl.bind(mainMod .. " + F",     hl.dsp.exec_cmd("librewolf"))
hl.bind(mainMod .. " + W",     hl.dsp.exec_cmd("chromium"))
hl.bind(mainMod .. " + G",     hl.dsp.exec_cmd(freetube))
hl.bind(mainMod .. " + D",     hl.dsp.exec_cmd(dbman))

hl.bind(mainMod .. " + M",     hl.dsp.window.fullscreen({ mode = "maximized" }))
hl.bind(mainMod .. " + z",     hl.dsp.exec_cmd("hyprlock"))
-- Panic exit from the neu shell: back to waybar/wofi/dunst, no files touched.
-- See NEU_THEME.md. This is the first of the three ways out.
hl.bind(mainMod .. " + SHIFT + ESCAPE", hl.dsp.exec_cmd("~/.local/bin/neu-panic.sh"))
-- The dock also reveals by pushing the pointer to the bottom edge.
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd("qs -c commandcenter ipc call dock toggle"))

-- Move focus with mainMod + vim keys
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Workspace switcher with wofi
-- Alt-tab. The switcher stays open across presses instead of respawning a
-- picker each time: first press opens it on the previously-used window, further
-- presses advance, releasing SUPER commits, Escape or a click dismisses.
hl.bind(mainMod .. " + TAB",         hl.dsp.exec_cmd("qs -c commandcenter ipc call switcher next"))
hl.bind(mainMod .. " + SHIFT + TAB", hl.dsp.exec_cmd("qs -c commandcenter ipc call switcher prev"))
-- Fallback commit: the switcher handles the SUPER release itself while it holds
-- keyboard focus, but the press that opened it happened before it had focus, so
-- the release may arrive as a modifier update rather than a key event. Harmless
-- when the switcher is closed -- confirm() returns immediately.
hl.bind(mainMod .. " + SUPER_L", hl.dsp.exec_cmd("qs -c commandcenter ipc call switcher confirm"), { release = true })

-- Command Center panel (tasks + time tracking + tmux projects)
-- `grave` is the bare ~ key, so no shift is needed to summon it.
hl.bind(mainMod .. " + grave", hl.dsp.exec_cmd("qs -c commandcenter ipc call dev toggle"))

-- rgtv at a glance: Prometheus alerts, Gitea PRs + CI, fleet health, Grafana
-- links. Same quickshell instance as the Command Center, other side of the screen.
hl.bind(mainMod .. " + R",     hl.dsp.exec_cmd("qs -c commandcenter ipc call rgtv toggle"))

-- Tmux project picker with wofi (also the fallback if quickshell is missing)
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("qs -c commandcenter ipc call cc toggle"))

-- Special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Move windows around
hl.bind(mainMod .. " + SHIFT + h", hl.dsp.window.swap({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.window.swap({ direction = "down" }))
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.window.swap({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.swap({ direction = "right" }))

-- Volume keys
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +5%"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -5%"))
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"))

-- Media keys (locked = active even when locked/inhibited)
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })
hl.bind("XF86AudioStop",  hl.dsp.exec_cmd("playerctl stop"),       { locked = true })

-- Brightness keys
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("~/.local/bin/brightness.sh --inc 250"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("~/.local/bin/brightness.sh --dec 250"))


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Bind workspaces 9 and 10 to second monitor (HDMI-A-1) when it's connected.
-- When HDMI-A-1 exists, ws 9 and 10 live there and the rest stay on the primary.
-- If the monitor is not connected, these workspaces fall back to the primary monitor.
hl.workspace_rule({ workspace = "9",  monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "10", monitor = "HDMI-A-1" })
