-- generated by theme/gen.py from theme/tokens.json; do not edit
--
-- Colours and metrics for hyprland.lua. Hyprland wants rgba(rrggbbaa).

return {
    bg = "rgba(141414ff)",
    bgComponent = "rgba(171717ff)",
    bgCard = "rgba(181818ff)",
    shadowDark = "rgba(000000ff)",
    shadowLight = "rgba(555555ff)",
    text = "rgba(ccccccff)",
    textMuted = "rgba(999999ff)",
    textDim = "rgba(888888ff)",
    primary = "rgba(8b2fe0ff)",
    secondary = "rgba(ff2e9aff)",
    tertiary = "rgba(15cdc3ff)",
    accent = "rgba(8b2fe099)",
    success = "rgba(a6e3a1ff)",
    error = "rgba(f38ba8ff)",
    warning = "rgba(fab387ff)",
    info = "rgba(89b4faff)",
    shadowDarkDim = "rgba(0000008c)",
    transparent = "rgba(00000000)",

    rounding = 16,
    border   = 1,
    gaps_in  = 7,
    gaps_out = 15,
    shadow_range  = 6,
    shadow_offset = 3,
    shadow_reach  = 15,

    -- Hyprland animation speed is in ds (1 = 100ms).
    speed_fast    = 2,
    speed_base    = 2,
    speed_default = 3,
    speed_rainbow = 100,
}
