#!/usr/bin/env python3
"""Export @rgtv/neu design tokens into every format this desktop speaks.

Single input:  theme/tokens.json
Outputs:       committed, generated files across the repo (see EMITTERS)

    python3 theme/gen.py           # write
    python3 theme/gen.py --check   # verify on-disk files match tokens (CI / pre-flight)
    python3 theme/gen.py --list    # show what would be written

Nothing here is hand-editable: change theme/tokens.json and re-run.

Colour maths mirrors the design system exactly --
  * shade ramps interpolate in OKLCh, like `color-mix(in oklch, ...)` in
    src/theme/variables.css and shade() in src/shade.ts
  * translucent "glow" tokens are `color-mix(in srgb, C n%, transparent)`,
    which in CSS keeps the hue and just sets alpha
  * two-colour srgb mixes lerp in gamma-encoded sRGB, as CSS does
"""

from __future__ import annotations

import json
import math
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TOKENS = ROOT / "theme" / "tokens.json"
TEMPLATES = ROOT / "theme" / "templates"

STAMP = "generated by theme/gen.py from theme/tokens.json; do not edit"


# ---------------------------------------------------------------- colour ----

def parse(h: str) -> tuple[float, float, float, float]:
    h = h.lstrip("#")
    if len(h) == 6:
        r, g, b, a = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16), 255
    elif len(h) == 8:
        r, g, b, a = (int(h[i:i + 2], 16) for i in (0, 2, 4, 6))
    else:
        raise ValueError(f"bad hex {h!r}")
    return r / 255, g / 255, b / 255, a / 255


def hexa(c: tuple[float, float, float, float]) -> str:
    r, g, b, a = c
    out = "#%02x%02x%02x" % tuple(max(0, min(255, round(v * 255))) for v in (r, g, b))
    if a < 1:
        out += "%02x" % max(0, min(255, round(a * 255)))
    return out


def rgb6(c) -> str:
    """Drop alpha entirely -- for formats with no alpha channel."""
    return "#%02x%02x%02x" % tuple(max(0, min(255, round(v * 255))) for v in c[:3])


def alpha(c, a: float):
    return (c[0], c[1], c[2], a)


def over(c, bg):
    """Composite c over opaque bg."""
    a = c[3]
    return tuple(c[i] * a + bg[i] * (1 - a) for i in range(3)) + (1.0,)


def mix_srgb(a, b, p: float):
    """`color-mix(in srgb, a p%, b)` -- gamma-encoded lerp, p in 0..100."""
    t = p / 100
    return tuple(a[i] * t + b[i] * (1 - t) for i in range(3)) + (a[3] * t + b[3] * (1 - t),)


# --- OKLab / OKLCh (Bjorn Ottosson's matrices, same path the browser takes) ---

def _lin(u):
    return u / 12.92 if u <= 0.04045 else ((u + 0.055) / 1.055) ** 2.4


def _unlin(u):
    return 12.92 * u if u <= 0.0031308 else 1.055 * (u ** (1 / 2.4)) - 0.055


def to_oklab(c):
    r, g, b = (_lin(v) for v in c[:3])
    l = 0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b
    m = 0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b
    s = 0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b
    l_, m_, s_ = (v ** (1 / 3) if v > 0 else -((-v) ** (1 / 3)) for v in (l, m, s))
    return (
        0.2104542553 * l_ + 0.7936177850 * m_ - 0.0040720468 * s_,
        1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_,
        0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_,
    )


def from_oklab(lab, a=1.0):
    L, A, B = lab
    l_ = L + 0.3963377774 * A + 0.2158037573 * B
    m_ = L - 0.1055613458 * A - 0.0638541728 * B
    s_ = L - 0.0894841775 * A - 1.2914855480 * B
    l, m, s = (v ** 3 for v in (l_, m_, s_))
    r = +4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s
    g = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s
    b = -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s
    return tuple(min(1.0, max(0.0, _unlin(v))) for v in (r, g, b)) + (a,)


def shade(c, pct: int):
    """color-mix(in oklch, c, white|black |pct|%) -- positive lightens.

    White and black are chroma-zero, so their hue is powerless: only L and C
    move, the hue is carried through unchanged. That is exactly why the DS
    mixes in OKLCh -- sRGB would wash the hue toward grey.
    """
    t = abs(pct) / 100
    L, A, B = to_oklab(c)
    C = math.hypot(A, B)
    H = math.atan2(B, A)
    L = L * (1 - t) + (1.0 if pct > 0 else 0.0) * t
    C = C * (1 - t)
    return from_oklab((L, C * math.cos(H), C * math.sin(H)), c[3])


# --- contrast, ported from src/contrast.ts + onAccent() in src/themes.ts ------

INK_LIGHT, INK_DARK = "#cdd6f4", "#11111b"
INK_LIGHT_MAX, INK_DARK_MAX = "#ffffff", "#000000"
AA_NORMAL = 4.5


def luminance(c) -> float:
    r, g, b = (_lin(v) for v in c[:3])
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(a, b) -> float:
    la, lb = luminance(a), luminance(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


def on_accent(face) -> str:
    """Readable ink for text sitting on `face`.

    Splits at the luminance where white and black contrast equally
    (sqrt(1.05 * 0.05) - 0.05), then escalates to a pure endpoint if the themed
    ink can't clear AA for normal text -- exactly what themes.ts does, which is
    why #8b2fe0 ends up with pure white rather than the themed #cdd6f4.
    """
    split = math.sqrt(1.05 * 0.05) - 0.05
    themed, maxed = ((INK_DARK, INK_DARK_MAX) if luminance(face) > split
                     else (INK_LIGHT, INK_LIGHT_MAX))
    return themed if contrast(parse(themed), face) >= AA_NORMAL else maxed


# ------------------------------------------------------------- resolution ----

class Theme:
    """Every token, resolved to concrete colours and numbers."""

    def __init__(self, t: dict):
        self.t = t
        self.ctp = {k: parse(v) for k, v in t["ctp"].items()}
        self.brand = {k: parse(v) for k, v in t["brand"].items()}
        self.surf = {k: parse(v) for k, v in t["surface"].items()}
        self.domain = {k: parse(v) for k, v in t["domain"].items()}

        self.bg = self.surf["bg"]
        self.primary = self.brand["primary"]
        self.secondary = self.brand["secondary"]
        self.tertiary = self.brand["tertiary"]

        # Translucent "glow" halves of each semantic pair.
        g = t["accentGlow"] / 100
        self.accent = alpha(self.primary, g)
        self.accentSecondary = alpha(self.secondary, g)
        self.accentTertiary = alpha(self.tertiary, g)

        self.status = {}
        for name, spec in t["status"].items():
            hue = self.ctp[spec["hue"]]
            self.status[name] = {"text": hue, "glow": alpha(hue, spec["glow"] / 100)}

        self.hairline = alpha(self.surf["textDim"], t["hairlineMix"] / 100)
        self.scrollThumb = mix_srgb(self.primary, self.surf["bgComponent"],
                                    t["scrollbar"]["thumbMix"])

    # -- helpers used by emitters -------------------------------------------

    def px(self, rem_key: str) -> int:
        return round(self.t["type"]["rem"][rem_key] * self.t["type"]["rootPx"])

    def ramp(self, base):
        return {k: shade(base, v) for k, v in self.t["shadeSteps"].items()}

    def flat(self) -> dict[str, str]:
        """Flat `{{name}}` namespace for templates. Values are CSS hex."""
        v: dict[str, str] = {}
        for k, c in self.ctp.items():
            v[f"ctp_{k}"] = hexa(c)
        for k, c in self.brand.items():
            v[k] = hexa(c)
        for k, c in self.surf.items():
            v[k] = hexa(c)
        v["accent"] = hexa(self.accent)
        v["accentSecondary"] = hexa(self.accentSecondary)
        v["accentTertiary"] = hexa(self.accentTertiary)
        v["hairline"] = hexa(self.hairline)
        v["scrollThumb"] = hexa(self.scrollThumb)
        for name, pair in self.status.items():
            v[name] = hexa(pair["text"])
            v[f"{name}Glow"] = hexa(pair["glow"])
        for name, base in (("accent", self.primary), ("secondary", self.secondary),
                           ("tertiary", self.tertiary)):
            for step, c in self.ramp(base).items():
                v[f"{name}_{step}"] = hexa(c)
        # opaque composites, for formats with no alpha
        v["accentOnBg"] = rgb6(over(self.accent, self.bg))
        v["hairlineOnBg"] = rgb6(over(self.hairline, self.surf["bgComponent"]))

        # Hyprland wants rgba(rrggbbaa) with no '#'
        for k in list(v):
            h = v[k].lstrip("#")
            v[f"hl_{k}"] = "rgba(%s)" % (h if len(h) == 8 else h + "ff")
        # QML/Qt want #aarrggbb
        for k in [k for k in v if not k.startswith("hl_")]:
            h = v[k].lstrip("#")
            v[f"qt_{k}"] = "#" + (h[6:8] + h[0:6] if len(h) == 8 else h)

        for k, n in self.t["size"].items():
            v[f"size_{k}"] = str(n)
        for k, n in self.t["radius"].items():
            v[f"radius_{k}"] = str(n)
        for k, n in self.t["border"].items():
            v[f"border_{k}"] = str(n)
        for k in self.t["type"]["rem"]:
            v[f"font_{k}"] = str(self.px(k))
        for k, n in self.t["type"]["weight"].items():
            v[f"weight_{k}"] = str(n)
        for k, n in self.t["motion"].items():
            v[k] = str(n)
        for k, n in self.t["type"]["font"].items():
            if not k.startswith("_"):
                v[f"family_{k}"] = n
        for k, n in self.t["desktop"].items():
            if isinstance(n, (int, float, str)) and not k.startswith("_"):
                v[f"desktop_{k}"] = str(n)
        d = self.t["desktop"]
        v["barHeight"] = str(d["barHeight"])
        v["barHeightPlusGap"] = str(d["barHeight"] + self.t["shadow"]["l"]["gap"])
        v["dockIconPx"] = str(d["dockIconPx"])
        v["user_name"] = self.t["desktop"]["user"]["name"]
        v["user_initials"] = self.t["desktop"]["user"]["initials"]
        v["wall_w"] = str(self.t["desktop"]["wallpaper"]["width"])
        v["wall_h"] = str(self.t["desktop"]["wallpaper"]["height"])
        v["wall_bloom"] = "1" if self.t["desktop"]["wallpaper"].get("style") == "bloom" else "0"
        v["focusRing"] = str(self.t["focusRing"])
        for k, sh in self.t["shadow"].items():
            if k.startswith("_"):
                continue
            v[f"shadow_{k}_offset"] = str(sh["offset"])
            v[f"shadow_{k}_blur"] = str(sh["blur"])
            v[f"shadow_{k}_gap"] = str(sh["gap"])
        for k in ("primary", "secondary", "tertiary"):
            v[f"ink_{k}"] = on_accent(getattr(self, k))
        for k, pair in self.status.items():
            v[f"ink_{k}"] = on_accent(pair["text"])
        for base in ("accent", "secondary", "tertiary"):
            for step, c in self.ramp(getattr(self, {"accent": "primary"}.get(base, base))).items():
                v[f"ink_{base}_{step}"] = on_accent(c)
        v["stamp"] = STAMP
        v["repo_root"] = str(ROOT)
        v["home"] = str(pathlib.Path.home())
        # hyprlock/hyprland animation speeds are in ds (1 = 100ms)
        for k in ("fast", "base", "default", "slow"):
            v[f"motion_{k}_ds"] = str(max(1, round(self.t["motion"][k + "Ms"] / 100)))
        return v


# ------------------------------------------------------------- templating ----

PLACEHOLDER = re.compile(r"\{\{([a-zA-Z0-9_]+)\}\}")


def render(name: str, flat: dict[str, str]) -> str:
    src = (TEMPLATES / name).read_text()
    missing: list[str] = []

    def sub(m):
        key = m.group(1)
        # {{u_e0b6}} -> the literal character. Nerd-font glyphs live in the BMP
        # private-use area and do not survive being written directly, so every
        # icon in a template is spelled by codepoint and materialised here.
        if re.fullmatch(r"u_[0-9a-fA-F]{4,6}", key):
            return chr(int(key[2:], 16))
        if key not in flat:
            missing.append(key)
            return m.group(0)
        return flat[key]

    out = PLACEHOLDER.sub(sub, src)
    if missing:
        raise SystemExit(f"{name}: unknown placeholder(s): {sorted(set(missing))}")
    return out


# --------------------------------------------------------------- emitters ----
# Each returns (repo-relative path, file contents). Data-shaped files are built
# here; files that interleave colour with layout live in theme/templates/.

def emit_theme_qml(T: Theme) -> tuple[str, str]:
    """quickshell/Theme.qml -- the shell's token singleton.

    Keeps every property name the pre-existing panes already bind to, so the
    shell keeps running the moment this is regenerated; the Catppuccin *greyscale*
    names (base/mantle/crust/surface*/overlay*/subtext*) are re-pointed at the neu
    ramp, while the *status* hues stay true Catppuccin, exactly as the DS does.
    """
    f = T.flat()
    q = lambda k: f["qt_" + k]  # noqa: E731
    t = T.t
    sh = t["shadow"]
    ins = t["shadowInset"]

    L = []
    a = L.append
    a("pragma Singleton\n")
    a("import QtQuick")
    a("import Quickshell\n")
    a(f"// {STAMP}")
    a("//")
    a("// @rgtv/neu v3.1.0 design tokens. Depth in this system comes from SHADOW,")
    a("// not surface contrast -- the three surface levels are only 4 values apart")
    a("// on purpose. Raised = pressable, inset = active/held, flat = disabled;")
    a("// see NeuSurface.qml, and don't break that grammar for decoration.")
    a("Singleton {")

    a("    // ---- surfaces -------------------------------------------------")
    for name, key in (("neuBg", "bg"), ("neuBgComponent", "bgComponent"),
                      ("neuBgCard", "bgCard"), ("neuHoverHighlight", "hoverHighlight"),
                      ("neuShadowDark", "shadowDark"), ("neuShadowLight", "shadowLight")):
        a(f'    readonly property color {name}: "{q(key)}"')

    a("\n    // ---- text -----------------------------------------------------")
    for name, key in (("neuText", "text"), ("neuTextMuted", "textMuted"),
                      ("neuTextDim", "textDim")):
        a(f'    readonly property color {name}: "{q(key)}"')
    a(f'    readonly property color neuHairline: "{q("hairline")}"')

    a("\n    // ---- brand ----------------------------------------------------")
    for name, key in (("neuAccentText", "primary"), ("neuAccent", "accent"),
                      ("neuAccentSecondaryText", "secondary"),
                      ("neuAccentSecondary", "accentSecondary"),
                      ("neuAccentTertiaryText", "tertiary"),
                      ("neuAccentTertiary", "accentTertiary")):
        a(f'    readonly property color {name}: "{q(key)}"')
    for base in ("accent", "secondary", "tertiary"):
        for step in t["shadeSteps"]:
            prop = "neu" + base.capitalize() + step.capitalize()
            a(f'    readonly property color {prop}: "{q(base + "_" + step)}"')

    a("\n    // ---- status (stays Catppuccin, as in the DS) -------------------")
    for name in T.status:
        a(f'    readonly property color neu{name.capitalize()}Text: "{q(name)}"')
        a(f'    readonly property color neu{name.capitalize()}: "{q(name + "Glow")}"')

    a("\n    // ---- categorical domain slots ---------------------------------")
    for k, c in T.domain.items():
        a(f'    readonly property color neuDomain{k}: "{rgb6(c)}"')

    a("\n    // ---- shadow ramp (offset / blur / reach) ----------------------")
    a("    // reach = offset + blur: space siblings by it so their shadows meet")
    a("    // rather than overlap. Straight from --neu-shadow-*-gap.")
    for k, s in sh.items():
        if k.startswith("_"):
            continue
        K = k.capitalize()
        a(f'    readonly property int shadow{K}Offset: {s["offset"]}')
        a(f'    readonly property int shadow{K}Blur: {s["blur"]}')
        a(f'    readonly property int shadow{K}Gap: {s["gap"]}')
    for k, s in ins.items():
        K = k.capitalize()
        a(f'    readonly property int inset{K}Offset: {s["offset"]}')
        a(f'    readonly property int inset{K}Blur: {s["blur"]}')

    a("\n    // ---- scale ----------------------------------------------------")
    for k, n in t["size"].items():
        a(f"    readonly property int size{k.capitalize()}: {n}")
    for k, n in t["radius"].items():
        a(f"    readonly property int radius{k.capitalize()}: {n}")
    for k, n in t["border"].items():
        a(f"    readonly property int border{k.capitalize()}: {n}")
    a(f'    readonly property int focusRing: {t["focusRing"]}')

    a("\n    // ---- type -----------------------------------------------------")
    a(f'    readonly property string fontFamily: "{t["type"]["font"]["shell"]}"')
    a(f'    readonly property string fontUi: "{t["type"]["font"]["ui"]}"')
    for k in t["type"]["rem"]:
        a(f"    readonly property int font{k.capitalize()}: {T.px(k)}")
    for k, n in t["type"]["weight"].items():
        a(f"    readonly property int weight{k.capitalize()}: {n}")
    for k, n in t["type"]["tracking"].items():
        if not k.startswith("_"):
            a(f"    readonly property real tracking{k.capitalize()}: {n}")

    a("\n    // ---- motion / z -----------------------------------------------")
    for k, n in t["motion"].items():
        a(f"    readonly property int {k}: {n}")
    for k, n in t["z"].items():
        a(f"    readonly property int z{k.capitalize()}: {n}")

    a("\n    // ---- desktop --------------------------------------------------")
    d = t["desktop"]
    a(f'    readonly property int barHeight: {d["barHeight"]}')
    a(f'    readonly property real barBlurAlpha: {d["barBlurAlpha"]}')
    a(f'    readonly property int dockIconPx: {d["dockIconPx"]}')
    a(f'    readonly property real dockMagHovered: {d["dockMagnify"]["hovered"]}')
    a(f'    readonly property real dockMagNeighbour: {d["dockMagnify"]["neighbour"]}')
    a(f'    readonly property int meterSegments: {d["meterSegments"]}')
    a(f'    readonly property string userName: "{d["user"]["name"]}"')
    a(f'    readonly property string userInitials: "{d["user"]["initials"]}"')

    a("\n    // ---- compatibility aliases ------------------------------------")
    a("    // The panes written before this port bind to Catppuccin names. The")
    a("    // greyscale ones now resolve to the neu ramp so nothing looks foreign;")
    a("    // the status hues are genuinely still Catppuccin.")
    alias = [
        ("base", "bg"), ("mantle", "bg"), ("crust", "shadowDark"),
        ("surface0", "bgComponent"), ("surface1", "hoverHighlight"),
        ("surface2", "shadowLight"),
        ("text", "text"), ("subtext1", "text"), ("subtext0", "textMuted"),
        ("overlay2", "textMuted"), ("overlay1", "textMuted"), ("overlay0", "textDim"),
        ("primary", "primary"), ("secondary", "secondary"),
        ("lightPrimary", "accent_light"), ("lightestPrimary", "accent_lighter"),
        ("darkPrimary", "accent_darker"),
        ("lightSecondary", "secondary_light"), ("lightestSecondary", "secondary_lighter"),
        ("darkSecondary", "secondary_darker"),
        # header colour: the DS paints the topbar title with the brand accent
        ("sapphire", "primary"),
    ]
    for name, key in alias:
        a(f'    readonly property color {name}: "{q(key)}"')
    for name in ("rosewater", "flamingo", "pink", "mauve", "red", "maroon", "peach",
                 "yellow", "green", "teal", "sky", "blue", "lavender"):
        a(f'    readonly property color {name}: "{rgb6(T.ctp[name])}"')

    a("\n    // Near-opaque on purpose. hyprland.lua asks for layer blur behind the")
    a("    // neu:* namespaces, but Hyprland 0.56.2 does not honour it, so without a")
    a("    // real backdrop a translucent panel just shows sharp text through itself.")
    a(f'    readonly property color panelBg: Qt.rgba(neuBgCard.r, neuBgCard.g, neuBgCard.b, {d["barBlurAlpha"]})')
    a("    readonly property color rowBg: neuBgComponent")
    a("    readonly property color rowHover: neuHoverHighlight")
    a(f'    readonly property int fontSize: {T.px("m")}')
    a(f'    readonly property int fontSizeSmall: {T.px("s")}')
    a(f'    readonly property int fontSizeHeader: {T.px("xl")}')
    a(f'    readonly property int padding: {t["size"]["m"]}')
    a(f'    readonly property int radius: {t["radius"]["m"]}')
    a("    readonly property int rowHeight: 30")
    a(f'    readonly property int animDuration: {t["motion"]["baseMs"]}')
    a("}")
    return "quickshell/Theme.qml", "\n".join(L) + "\n"


def emit_hypr_lua(T: Theme) -> tuple[str, str]:
    f = T.flat()
    t = T.t
    L = [f"-- {STAMP}", "--", "-- Colours and metrics for hyprland.lua. Hyprland wants rgba(rrggbbaa).", "",
         "return {"]
    for k in ("bg", "bgComponent", "bgCard", "shadowDark", "shadowLight",
              "text", "textMuted", "textDim", "primary", "secondary", "tertiary",
              "accent", "success", "error", "warning", "info"):
        L.append(f'    {k} = "{f["hl_" + k]}",')
    # Half-strength light for an unfocused window's shadow pair.
    # Half-strength dark for an unfocused window's shadow.
    dim = hexa(alpha(T.surf["shadowDark"], 0.55)).lstrip("#")
    L.append(f'    shadowDarkDim = "rgba({dim})",')
    L.append('    transparent = "rgba(00000000)",')
    L.append("")
    L.append(f'    rounding = {t["radius"]["m"]},')
    # Its own token, not focusRing: the animated brand border is a window
    # decoration, and thinning it should not also thin the shell's focus rings
    # or hyprlock's input outline.
    L.append(f'    border   = {t["desktop"]["windowBorder"]},')
    L.append(f'    gaps_in  = {t["shadow"]["l"]["gap"] // 2},')
    L.append(f'    gaps_out = {t["shadow"]["l"]["gap"]},')
    # Which rung of the shadow ramp a window wears. `l` matches the DS's
    # .neu-window, but a window is far larger than a card and the halo scales
    # with the surface it surrounds, so a lower tier reads truer at this size.
    wtier = t["shadow"][t["desktop"]["windowShadowTier"]]
    L.append(f'    shadow_range  = {wtier["blur"]},')
    L.append(f'    shadow_offset = {wtier["offset"]},')
    # Full reach of the raised pair (offset + blur) -- what a single
    # zero-offset gradient shadow needs to cover the same ground.
    L.append(f'    shadow_reach  = {t["shadow"]["l"]["gap"]},')
    L.append("")
    L.append("    -- Hyprland animation speed is in ds (1 = 100ms).")
    L.append(f'    speed_fast    = {round(t["motion"]["fastMs"] / 100)},')
    L.append(f'    speed_base    = {round(t["motion"]["baseMs"] / 100)},')
    L.append(f'    speed_default = {round(t["motion"]["defaultMs"] / 100)},')
    # Hyprland clamps animation speed to 100 ds (10s); the DS rainbow is 20s.
    L.append(f'    speed_rainbow = {min(100, round(t["motion"]["rainbowMs"] / 100))},')
    L.append("}")
    return "hypr/neu.lua", "\n".join(L) + "\n"


def emit_waybar_css(T: Theme) -> tuple[str, str]:
    f = T.flat()
    L = [f"/* {STAMP} */", "/* Fallback bar only -- the Quickshell bar is the real one. */", ""]
    for name in ("bg", "bgComponent", "bgCard", "hoverHighlight", "shadowDark",
                 "shadowLight", "text", "textMuted", "textDim",
                 "primary", "secondary", "tertiary",
                 "success", "error", "warning", "info"):
        L.append(f"@define-color {name} {f[name]};")
    for name in ("green", "red", "peach", "yellow", "blue", "mauve", "lavender", "teal"):
        L.append(f"@define-color ctp_{name} {f['ctp_' + name]};")
    return "waybar/neu.css", "\n".join(L) + "\n"


def emit_reference_css(T: Theme) -> tuple[str, str]:
    """theme/neu.css -- every token as literal CSS, for eyeballing against the DS."""
    f = T.flat()
    t = T.t
    L = [f"/* {STAMP} */",
         "/* The resolved dark theme, flattened (no color-mix/oklch left to evaluate).",
         "   Diff this against ~/dev/rgtv-ds/src/theme/variables.css to see drift. */",
         "", ":root {"]
    for k in ("bg", "bgComponent", "bgCard", "hoverHighlight", "shadowDark", "shadowLight",
              "text", "textMuted", "textDim"):
        L.append(f"  --neu-{re.sub(r'(?<!^)(?=[A-Z])', '-', k).lower()}: {f[k]};")
    L.append(f"  --neu-accent: {f['accent']};")
    L.append(f"  --neu-accent-text: {f['primary']};")
    L.append(f"  --neu-accent-secondary: {f['accentSecondary']};")
    L.append(f"  --neu-accent-secondary-text: {f['secondary']};")
    L.append(f"  --neu-accent-tertiary: {f['accentTertiary']};")
    L.append(f"  --neu-accent-tertiary-text: {f['tertiary']};")
    for n in T.status:
        L.append(f"  --neu-{n}: {f[n + 'Glow']};")
        L.append(f"  --neu-{n}-text: {f[n]};")
    for base in ("accent", "secondary", "tertiary"):
        for step in t["shadeSteps"]:
            nm = "accent" if base == "accent" else f"accent-{base}"
            L.append(f"  --neu-{nm}-{step}: {f[f'{base}_{step}']};")
    for k, s in t["shadow"].items():
        if k.startswith("_"):
            continue
        o, b = s["offset"], s["blur"]
        L.append(f"  --neu-shadow-{k}: {o}px {o}px {b}px {f['shadowDark']}, "
                 f"-{o}px -{o}px {b}px {f['shadowLight']};")
        L.append(f"  --neu-shadow-{k}-gap: {s['gap']}px;")
    for k, s in t["shadowInset"].items():
        o, b = s["offset"], s["blur"]
        L.append(f"  --neu-shadow-inset-{k}: inset {o}px {o}px {b}px {f['shadowDark']}, "
                 f"inset -{o}px -{o}px {b}px {f['shadowLight']};")
    L.append(f"  --neu-focus-shadow: 0 0 0 {t['focusRing']}px {f['accent']};")
    L.append(f"  --neu-border-hairline-color: {f['hairline']};")
    for k, n in t["size"].items():
        L.append(f"  --neu-size-{k}: {n}px;")
    for k, n in t["radius"].items():
        L.append(f"  --neu-radius-{k}: {n}px;")
    for k, v in t["type"]["rem"].items():
        L.append(f"  --neu-font-{k}: {v}rem; /* {T.px(k)}px */")
    L.append(f"  --neu-transition-fast: {t['motion']['fastMs'] / 1000}s;")
    L.append(f"  --neu-transition-base: {t['motion']['baseMs'] / 1000}s;")
    L.append(f"  --neu-transition: {t['motion']['defaultMs'] / 1000}s;")
    L.append(f"  --neu-scrollbar-thumb: {f['scrollThumb']};")
    L.append("}")
    return "theme/neu.css", "\n".join(L) + "\n"


def ansi_palette(T: Theme) -> list[tuple[str, tuple]]:
    """The 16 ANSI slots.

    Greys 0/7/8/15 come from the neu surface ramp, so a terminal sits on the
    same ground as the shell. red/green/yellow/blue stay Catppuccin because the
    DS keeps its *status* hues Catppuccin. magenta/cyan take the brand secondary
    and tertiary -- they aren't status colours, so they're where the brand lands.
    """
    c = T.ctp
    s = T.surf
    return [
        ("black", s["hoverHighlight"]), ("red", c["red"]), ("green", c["green"]),
        ("yellow", c["yellow"]), ("blue", c["blue"]), ("magenta", T.secondary),
        ("cyan", T.tertiary), ("white", s["text"]),
        ("brblack", s["shadowLight"]), ("brred", shade(c["red"], 15)),
        ("brgreen", shade(c["green"], 15)), ("bryellow", shade(c["yellow"], 15)),
        ("brblue", shade(c["blue"], 15)), ("brmagenta", shade(T.secondary, 15)),
        ("brcyan", shade(T.tertiary, 15)), ("brwhite", (1.0, 1.0, 1.0, 1.0)),
    ]


def emit_kitty(T: Theme) -> tuple[str, str]:
    p = ansi_palette(T)
    s = T.surf
    sel = over(T.accent, T.bg)
    L = [f"# {STAMP}", "# Included from kitty.conf.", "",
         f"font_family      {T.t['type']['font']['mono']}",
         "bold_font        auto", "italic_font      auto", "bold_italic_font auto", "",
         f"foreground              {rgb6(s['text'])}",
         f"background              {rgb6(s['bg'])}",
         f"selection_foreground    #ffffff",
         f"selection_background    {rgb6(sel)}",
         f"cursor                  {rgb6(T.primary)}",
         f"cursor_text_color       {rgb6(s['bg'])}",
         f"url_color               {rgb6(T.tertiary)}",
         f"active_border_color     {rgb6(T.primary)}",
         f"inactive_border_color   {rgb6(s['shadowLight'])}",
         f"bell_border_color       {rgb6(T.ctp['peach'])}",
         f"active_tab_foreground   #ffffff",
         f"active_tab_background   {rgb6(T.primary)}",
         f"inactive_tab_foreground {rgb6(s['textMuted'])}",
         f"inactive_tab_background {rgb6(s['bgComponent'])}",
         f"tab_bar_background      {rgb6(s['bg'])}", ""]
    for i, (name, c) in enumerate(p):
        L.append(f"color{i:<2}                 {rgb6(c)}  # {name}")
    return "kitty/neu.conf", "\n".join(L) + "\n"


def emit_ghostty(T: Theme) -> tuple[str, str]:
    p = ansi_palette(T)
    s = T.surf
    L = [f"# {STAMP}", "# ghostty theme file: `theme = neu` in ghostty/config.", ""]
    for i, (name, c) in enumerate(p):
        L.append(f"palette = {i}={rgb6(c)}")
    L += ["",
          f"background = {rgb6(s['bg']).lstrip('#')}",
          f"foreground = {rgb6(s['text']).lstrip('#')}",
          f"cursor-color = {rgb6(T.primary).lstrip('#')}",
          f"cursor-text = {rgb6(s['bg']).lstrip('#')}",
          f"selection-background = {rgb6(over(T.accent, T.bg)).lstrip('#')}",
          "selection-foreground = ffffff"]
    return "ghostty/themes/neu", "\n".join(L) + "\n"


def emit_alacritty(T: Theme) -> tuple[str, str]:
    p = dict(ansi_palette(T))
    s = T.surf
    L = [f"# {STAMP}", "", "[colors.primary]",
         f'background = "{rgb6(s["bg"])}"', f'foreground = "{rgb6(s["text"])}"', "",
         "[colors.cursor]", f'cursor = "{rgb6(T.primary)}"', f'text = "{rgb6(s["bg"])}"', "",
         "[colors.selection]",
         f'background = "{rgb6(over(T.accent, T.bg))}"', 'text = "#ffffff"', ""]
    for group, pre in (("normal", ""), ("bright", "br")):
        L.append(f"[colors.{group}]")
        for n in ("black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"):
            L.append(f'{n} = "{rgb6(p[pre + n])}"')
        L.append("")
    return "alacritty/neu.toml", "\n".join(L).rstrip() + "\n"


def emit_tmux(T: Theme) -> tuple[str, str]:
    f = T.flat()
    L = [f"# {STAMP}",
         "# Sourced AFTER the catppuccin plugin loads, so these win.",
         "# catppuccin/tmux reads @thm_* -- repointing them re-skins the whole status line.",
         ""]
    m = [("bg", "bg"), ("mantle", "bg"), ("crust", "shadowDark"),
         ("surface_0", "bgComponent"), ("surface_1", "hoverHighlight"),
         ("surface_2", "shadowLight"),
         ("fg", "text"), ("subtext_1", "text"), ("subtext_0", "textMuted"),
         ("overlay_2", "textMuted"), ("overlay_1", "textMuted"), ("overlay_0", "textDim"),
         ("mauve", "primary"), ("pink", "secondary"), ("teal", "tertiary"),
         ("sapphire", "primary"), ("lavender", "accent_light"),
         ("green", "success"), ("red", "error"), ("peach", "warning"), ("blue", "info"),
         ("yellow", "ctp_yellow"), ("sky", "tertiary"), ("flamingo", "secondary_light"),
         ("rosewater", "text"), ("maroon", "error")]
    for name, key in m:
        L.append(f'set -ogq @thm_{name} "{f[key]}"')
    L += ["",
          f'set -ogq @thm_primary "{f["primary"]}"',
          f'set -ogq @thm_secondary "{f["secondary"]}"']
    return "tmux_conf/neu.conf", "\n".join(L) + "\n"


def emit_qt6ct(T: Theme) -> tuple[str, str]:
    """A qt6ct/qt5ct colour scheme: 3 states x 21 roles of #aarrggbb."""
    f, s = T.flat(), T.surf
    q = lambda c: "#ff" + rgb6(c).lstrip("#")  # noqa: E731
    win, base, txt = s["bg"], s["bgComponent"], s["text"]
    dis = s["textDim"]
    roles = {
        "WindowText": txt, "Button": s["bgComponent"], "Light": s["shadowLight"],
        "Midlight": s["hoverHighlight"], "Dark": s["shadowDark"], "Mid": s["hoverHighlight"],
        "Text": txt, "BrightText": (1.0, 1.0, 1.0, 1.0), "ButtonText": txt,
        "Base": base, "Window": win, "Shadow": s["shadowDark"],
        "Highlight": T.primary, "HighlightedText": (1.0, 1.0, 1.0, 1.0),
        "Link": T.tertiary, "LinkVisited": T.secondary,
        "AlternateBase": s["bgCard"], "NoRole": win,
        "ToolTipBase": s["bgCard"], "ToolTipText": txt, "PlaceholderText": s["textMuted"],
    }
    order = ["WindowText", "Button", "Light", "Midlight", "Dark", "Mid", "Text",
             "BrightText", "ButtonText", "Base", "Window", "Shadow", "Highlight",
             "HighlightedText", "Link", "LinkVisited", "AlternateBase", "NoRole",
             "ToolTipBase", "ToolTipText", "PlaceholderText"]
    active = ", ".join(q(roles[r]) for r in order)
    disabled = ", ".join(q(dis if r in ("WindowText", "Text", "ButtonText",
                                        "PlaceholderText") else roles[r]) for r in order)
    return "qt6ct/neu.conf", (
        f"# {STAMP}\n[ColorScheme]\n"
        f"active_colors={active}\n"
        f"disabled_colors={disabled}\n"
        f"inactive_colors={active}\n")


def emit_shell_colors(T: Theme) -> tuple[str, str]:
    """bin/neu-colors.sh -- truecolor escapes for _motd and sysinfo.sh."""
    f, s = T.flat(), T.surf
    def esc(c):
        r, g, b = (round(v * 255) for v in c[:3])
        return f"\\033[38;2;{r};{g};{b}m"
    pairs = [("NEU_ACCENT", T.primary), ("NEU_ACCENT2", T.secondary),
             ("NEU_ACCENT3", T.tertiary), ("NEU_TEXT", s["text"]),
             ("NEU_MUTED", s["textMuted"]), ("NEU_DIM", s["textDim"]),
             ("NEU_SUCCESS", T.status["success"]["text"]),
             ("NEU_ERROR", T.status["error"]["text"]),
             ("NEU_WARNING", T.status["warning"]["text"]),
             ("NEU_INFO", T.status["info"]["text"])]
    L = [f"# {STAMP}",
         "# ANSI truecolor escapes. `source` this; use with printf/echo -e.", ""]
    for name, c in pairs:
        L.append(f"{name}='{esc(c)}'   # {rgb6(c)}")
    L.append("NEU_RESET='\\033[0m'")
    return "bin/neu-colors.sh", "\n".join(L) + "\n"


TEMPLATED = [
    ("hyprlock.conf.in", "hypr/hyprlock.conf"),
    ("wofi-style.css.in", "wofi/style.css"),
    ("dunstrc.in", "dunst/dunstrc"),
    ("gtk3.css.in", "gtk/gtk.css"),
    ("gtk4.css.in", "gtk4/gtk.css"),
    ("qt6ct.conf.in", "qt6ct/qt6ct.conf"),
    ("starship.toml.in", "starship/starship.toml"),
    ("wallpaper.svg.in", "theme/wall/neu.svg"),
    ("avatar.svg.in", "theme/wall/neu-avatar.svg"),
]

EMITTERS = [emit_theme_qml, emit_hypr_lua, emit_waybar_css, emit_reference_css,
            emit_kitty, emit_ghostty, emit_alacritty, emit_tmux, emit_qt6ct,
            emit_shell_colors]


def build(T: Theme) -> dict[str, str]:
    out: dict[str, str] = {}
    for fn in EMITTERS:
        path, body = fn(T)
        out[path] = body
    flat = T.flat()
    for tpl, dest in TEMPLATED:
        out[dest] = render(tpl, flat)
    return out


def rasterize(T: Theme) -> list[str]:
    """SVG -> PNG. rsvg-convert is present on this box; Pillow is not."""
    import shutil
    import subprocess
    exe = shutil.which("rsvg-convert")
    if not exe:
        print("  !  rsvg-convert missing; skipping rasters", file=sys.stderr)
        return []
    w = T.t["desktop"]["wallpaper"]["width"]
    h = T.t["desktop"]["wallpaper"]["height"]
    jobs = [("theme/wall/neu.svg", f"theme/wall/neu-{w}x{h}.png", w, h),
            ("theme/wall/neu-avatar.svg", "theme/wall/neu-avatar.png", 256, 256)]
    done = []
    for src, dst, w_, h_ in jobs:
        s_, d_ = ROOT / src, ROOT / dst
        if not s_.exists():
            continue
        subprocess.run([exe, "-w", str(w_), "-h", str(h_), "-o", str(d_), str(s_)],
                       check=True)
        done.append(dst)
    return done


def scan_literal_glyphs() -> list[str]:
    """Any literal BMP private-use character that reached a QML file is a bug.

    Nerd-font glyphs in U+E000-F8FF get silently dropped between an editor and
    the disk, leaving an empty string that looks fine in a diff. Everything must
    go through Icons.qml (generated) or a \\uXXXX escape.
    """
    bad = []
    for f in sorted((ROOT / "quickshell").rglob("*.qml")):
        for i, line in enumerate(f.read_text().splitlines(), 1):
            for c in line:
                if 0xE000 <= ord(c) <= 0xF8FF:
                    bad.append(f"{f.relative_to(ROOT)}:{i}: literal U+{ord(c):04X}")
    return bad


def main(argv: list[str]) -> int:
    check = "--check" in argv
    listing = "--list" in argv
    T = Theme(json.loads(TOKENS.read_text()))
    out = build(T)

    if listing:
        for p in sorted(out):
            print(p)
        return 0

    drift = []
    for rel, body in sorted(out.items()):
        dest = ROOT / rel
        current = dest.read_text() if dest.exists() else None
        if current == body:
            continue
        if check:
            drift.append(rel)
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(body)
        print(f"  {'+' if current is None else 'M'} {rel}")

    glyphs = scan_literal_glyphs()
    if glyphs and check:
        print("literal private-use glyphs found (use Icons.qml or a \\uXXXX escape):",
              file=sys.stderr)
        for g in glyphs:
            print(f"  {g}", file=sys.stderr)

    if check:
        if drift:
            print("out of date (run `python3 theme/gen.py`):", file=sys.stderr)
            for d in drift:
                print(f"  {d}", file=sys.stderr)
        if drift or glyphs:
            return 1
        print("all generated files match theme/tokens.json; no literal glyphs on disk")
        return 0

    for png in rasterize(T):
        print(f"  M {png}")
    return 0



def qml_escape(cp: str) -> str:
    """Codepoint hex -> a QML/JS string escape (surrogate pair above the BMP)."""
    n = int(cp, 16)
    if n <= 0xFFFF:
        return "\\u%04x" % n
    v = n - 0x10000
    return "\\u%04x\\u%04x" % (0xD800 + (v >> 10), 0xDC00 + (v & 0x3FF))


def emit_icons_qml(T: Theme) -> tuple[str, str]:
    """quickshell/Icons.qml -- every nerd glyph, by codepoint.

    Literal private-use characters get silently dropped somewhere between an
    editor and the disk (it has already happened once in this repo: the timew
    segment's symbol was an empty string). Generating them from hex means a glyph
    can never go missing without theme/tokens.json changing.
    """
    ic = T.t["icons"]
    L = ["pragma Singleton", "", "import QtQuick", "import Quickshell", "",
         f"// {STAMP}", "//",
         "// Nerd-font glyphs, written as escapes rather than literal characters.",
         "// Every codepoint here is verified present in UbuntuMono Nerd Font.",
         "Singleton {"]
    for k, v in ic.items():
        if k.startswith("_"):
            continue
        if isinstance(v, list):
            items = ", ".join(f'"{qml_escape(c)}"' for c in v)
            L.append(f"    readonly property var {k}: [{items}]")
        else:
            L.append(f'    readonly property string {k}: "{qml_escape(v)}"')
    L.append("")
    L.append("    /** Pick from a low->high ramp by a 0..1 fraction. */")
    L.append("    function ramp(list, frac) {")
    L.append("        if (!list || list.length === 0) return \"\";")
    L.append("        const i = Math.round(Math.max(0, Math.min(1, frac)) * (list.length - 1));")
    L.append("        return list[i];")
    L.append("    }")
    L.append("}")
    return "quickshell/Icons.qml", "\n".join(L) + "\n"


EMITTERS.append(emit_icons_qml)

if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
